### ISSUE TITLE
Only 'Started' notifications are visible in Rocketchat.

### ISSUE THREAD

**Issue by djibi2** [hypery2k/rocket-chat-notifier#11]
OS: Ubuntu 14.04.5
Jenkins Version: 2.27
java version: java-7-openjdk-amd64
RocketChat version:  1.3.1
rocket-chat-notifier: 0.2.2-SNAPSHOT 

I have successfully configured the plugin to send all notifications to rocket chat, but I only see the "Started" notifications in Rocketchat.

![screenshot from 2016-10-28 10 16 06](https://cloud.githubusercontent.com/assets/5270930/19811598/b7b2b586-9cf7-11e6-99d4-4546b9575731.png)

![image](https://cloud.githubusercontent.com/assets/5270930/19811647/ebc0f2d4-9cf7-11e6-937f-2e507add0180.png)

In the Jenkins logs it does look the the events for other messages are present:

`Invoking Started...
Oct 28, 2016 10:14:23 AM INFO hudson.model.Run execute rocket chat test #14 main build action completed: SUCCESS
Oct 28, 2016 10:14:46 AM INFO jenkins.plugins.rocketchatnotifier.RocketChatNotifier prebuild

Invoking Started...
Oct 28, 2016 10:14:47 AM INFO hudson.model.Run execute rocket chat test #15 main build action completed: FAILURE
`

**Comment by hypery2k** [comment]
Closed due to fact that issues are tracked here: https://issues.jenkins-ci.org/browse/JENKINS-39690
